make:
	g++ main.cpp -lraylib -lm -ldl -lpthread -lGL -lrt -lX11

run:
	g++ main.cpp -lraylib -lm -ldl -lpthread -lGL -lrt -lX11
	./a.out
lines:
	wc -l makefile
	wc -l main.cpp
	wc -l lib/*
	wc -l entities/*

